export type AuthUser = {
  id: number;
  email: string;
  role: string;
  permissions: string[];
};

export type LoginResponse = {
  token: string;
  user: AuthUser;
};

export const Permission = {
  DashboardView: "dashboard.view",
  HeroView: "hero.view",
  HeroCreate: "hero.create",
  HeroEdit: "hero.edit",
  HeroDelete: "hero.delete",
  HeroManage: "hero.view",
  AboutManage: "about.view",
  AboutView: "about.view",
  AboutCreate: "about.create",
  AboutEdit: "about.edit",
  AboutDelete: "about.delete",
  ServicesManage: "services.view",
  ServicesView: "services.view",
  ServicesCreate: "services.create",
  ServicesEdit: "services.edit",
  ServicesDelete: "services.delete",
  TrainersManage: "trainers.view",
  TrainersView: "trainers.view",
  TrainersCreate: "trainers.create",
  TrainersEdit: "trainers.edit",
  TrainersDelete: "trainers.delete",
  MembershipManage: "membership.view",
  MembershipView: "membership.view",
  MembershipCreate: "membership.create",
  MembershipEdit: "membership.edit",
  MembershipDelete: "membership.delete",
  GalleryManage: "gallery.view",
  GalleryView: "gallery.view",
  GalleryCreate: "gallery.create",
  GalleryEdit: "gallery.edit",
  GalleryDelete: "gallery.delete",
  TestimonialsManage: "testimonials.view",
  TestimonialsView: "testimonials.view",
  TestimonialsCreate: "testimonials.create",
  TestimonialsEdit: "testimonials.edit",
  TestimonialsDelete: "testimonials.delete",
  ContactManage: "contact.view",
  ContactView: "contact.view",
  ContactEdit: "contact.edit",
  SettingsView: "settings.view",
  SettingsEdit: "settings.edit",
  SettingsManage: "settings.view",
  RolesManage: "roles.view",
  UsersView: "users.view",
  UsersCreate: "users.create",
  UsersEdit: "users.edit",
  UsersDelete: "users.delete",
  MembersView: "members.view",
  MembersCreate: "members.create",
  MembersEdit: "members.edit",
  FeesView: "fees.view",
  FeesCreate: "fees.create",
  FeesEdit: "fees.edit",
  NotificationsView: "notifications.view",
  NotificationsEdit: "notifications.edit",
  EnquiriesView: "enquiries.view",
  EnquiriesEdit: "enquiries.edit",
  ProductsView: "products.view",
  ProductsCreate: "products.create",
  ProductsEdit: "products.edit",
  ProductsDelete: "products.delete",
} as const;
