import { useEffect, useState } from "react";
import { apiFetch } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";
import { Permission } from "../../types/auth";

type Plan = { id: number; name: string; shortDescription: string; description: string; price: number; durationMonths: number; features: string; displayOrder: number; isPopular: boolean; isActive: boolean };
type PlanForm = Omit<Plan, "id">;
const emptyForm: PlanForm = { name: "", shortDescription: "", description: "", price: 0, durationMonths: 1, features: "", displayOrder: 0, isPopular: false, isActive: true };

export function MembershipPlansPage() {
  const { hasPermission } = useAuth();
  const [records, setRecords] = useState<Plan[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null);
  const [form, setForm] = useState<PlanForm>(emptyForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const canView = hasPermission(Permission.MembershipView); const canCreate = hasPermission(Permission.MembershipCreate); const canEdit = hasPermission(Permission.MembershipEdit); const canDelete = hasPermission(Permission.MembershipDelete);
  useEffect(() => { if (!canView) { setLoading(false); return; } void (async () => { try { setRecords(await apiFetch<Plan[]>("/api/membership-plans/all")); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to load plans." }); } finally { setLoading(false); } })(); }, [canView]);
  function update<K extends keyof PlanForm>(key: K, value: PlanForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function select(id: number) { const plan = records.find((item) => item.id === id); if (plan) { setSelectedId(id); setForm(plan); setMessage(null); } }
  async function save() {
    if (!form.name.trim() || !form.shortDescription.trim()) { setMessage({ type: "error", text: "Name and short description are required." }); return; }
    if (form.price < 0 || form.durationMonths <= 0 || form.displayOrder < 0) { setMessage({ type: "error", text: "Check price, duration, and display order values." }); return; }
    if (selectedId ? !canEdit : !canCreate) { setMessage({ type: "error", text: "You do not have permission to save plans." }); return; }
    setSaving(true); try { const result = await apiFetch<Plan>(selectedId ? `/api/membership-plans/${selectedId}` : "/api/membership-plans", { method: selectedId ? "PUT" : "POST", body: JSON.stringify(form) }); setRecords((current) => (selectedId ? current.map((item) => item.id === result.id ? result : item) : [...current, result]).sort((a, b) => a.displayOrder - b.displayOrder)); setSelectedId(result.id); setForm(result); setMessage({ type: "success", text: "Membership plan saved successfully." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to save plan." }); } finally { setSaving(false); }
  }
  async function remove() { if (!selectedId || !canDelete || !window.confirm("Delete this membership plan?")) return; try { await apiFetch(`/api/membership-plans/${selectedId}`, { method: "DELETE" }); setRecords((current) => current.filter((item) => item.id !== selectedId)); setSelectedId(null); setForm(emptyForm); setMessage({ type: "success", text: "Membership plan deleted." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to delete plan." }); } }
  if (!canView) return <main className="page"><h1>Membership Plans</h1><p>You do not have permission to view this page.</p></main>;
  return <main className="page cms-page"><div className="page-header"><div><h1>Membership Plans</h1><p className="muted">Manage public membership pricing.</p></div></div>{message ? <p className={`info ${message.type}`}>{message.text}</p> : null}{loading ? <p>Loading plans…</p> : <div className="cms-layout"><aside className="card cms-list"><button className="btn" onClick={() => { setSelectedId(null); setForm(emptyForm); setMessage(null); }} disabled={!canCreate}>New Plan</button>{records.map((plan) => <button className={`cms-list-item${plan.id === selectedId ? " selected" : ""}`} key={plan.id} onClick={() => select(plan.id)}><span>{plan.displayOrder}. {plan.name}</span><small>{plan.isPopular ? "Popular" : plan.isActive ? "Active" : "Inactive"}</small></button>)}</aside><section className="card cms-form"><div className="form-grid"><div className="form-field"><label>Name<input value={form.name} onChange={(event) => update("name", event.target.value)} /></label></div><div className="form-field"><label>Short Description<input value={form.shortDescription} onChange={(event) => update("shortDescription", event.target.value)} /></label></div></div><div className="form-field"><label>Full Description<textarea rows={4} value={form.description} onChange={(event) => update("description", event.target.value)} /></label></div><div className="form-field"><label>Features<textarea rows={6} placeholder={"Personal Training\nGym Access\nProgress Tracking"} value={form.features} onChange={(event) => update("features", event.target.value)} /></label></div><div className="form-grid stats-inputs"><div className="form-field"><label>Price<input type="number" min="0" step="0.01" value={form.price} onChange={(event) => update("price", Number(event.target.value))} /></label></div><div className="form-field"><label>Duration Months<input type="number" min="1" value={form.durationMonths} onChange={(event) => update("durationMonths", Number(event.target.value))} /></label></div><div className="form-field"><label>Display Order<input type="number" min="0" value={form.displayOrder} onChange={(event) => update("displayOrder", Number(event.target.value))} /></label></div></div><div className="cms-form-footer"><label className="toggle-row"><input type="checkbox" checked={form.isPopular} onChange={(event) => update("isPopular", event.target.checked)} /> Popular</label><label className="toggle-row"><input type="checkbox" checked={form.isActive} onChange={(event) => update("isActive", event.target.checked)} /> Active</label><button className="btn" onClick={save} disabled={saving || (selectedId ? !canEdit : !canCreate)}>{saving ? "Saving…" : selectedId ? "Save Changes" : "Create Plan"}</button>{selectedId && canDelete ? <button className="btn btn-danger" onClick={remove}>Delete</button> : null}</div></section></div>}</main>;
}
