import { useEffect, useState, type FormEvent } from "react";

type Contact = { gymName: string; address: string; phone: string; email: string; openingHours: string; googleMapsUrl: string; instagramUrl: string; facebookUrl: string; whatsAppNumber: string; description: string };
const apiUrl = import.meta.env.VITE_API_URL ?? "http://localhost:5182";
export function ContactPage() {
  const [contact, setContact] = useState<Contact | null>(null);
  const [form, setForm] = useState({ name: "", email: "", phone: "", message: "" });
  const [sent, setSent] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${apiUrl}/api/contact`).then(async (response) => { if (!response.ok) throw new Error(); return await response.json() as Contact; }).then(setContact).catch(() => setContact(null)).finally(() => setLoading(false)); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSent(""); try { const response = await fetch(`${apiUrl}/api/enquiries`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(); setForm({ name: "", email: "", phone: "", message: "" }); setSent("Thanks! Your enquiry has been sent."); } catch { setSent("Unable to send your enquiry. Please try again."); } }
  return <main className="contact-page"><section className="contact-section contact-route-section"><div className="contact-heading"><span className="eyebrow">Get in touch</span><h1>Let's get<br />you moving.</h1>{contact?.description ? <p>{contact.description}</p> : null}</div>{loading ? <p className="contact-empty">Loading contact information…</p> : contact ? <div className="contact-layout"><div className="contact-details">{contact.gymName ? <div><small>Gym</small><strong>{contact.gymName}</strong></div> : null}{contact.address ? <div><small>Address</small><strong>{contact.address}</strong></div> : null}{contact.phone ? <div><small>Phone</small><a href={`tel:${contact.phone}`}>{contact.phone}</a></div> : null}{contact.email ? <div><small>Email</small><a href={`mailto:${contact.email}`}>{contact.email}</a></div> : null}{contact.openingHours ? <div><small>Opening Hours</small><strong>{contact.openingHours}</strong></div> : null}</div><div className="contact-actions">{contact.googleMapsUrl ? <a className="contact-button contact-button-primary" href={contact.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <span>↗</span></a> : null}{contact.whatsAppNumber ? <a className="contact-button" href={`https://wa.me/${contact.whatsAppNumber.replace(/\D/g, "")}`}>WhatsApp <span>↗</span></a> : null}</div></div> : <p className="contact-empty">Contact information is coming soon.</p>}<form className="enquiry-form" onSubmit={submit}><h2>Send an enquiry</h2><div><input required placeholder="Your name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input required type="email" placeholder="Email address" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /><input placeholder="Phone number" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></div><textarea required rows={5} placeholder="How can we help?" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /><button className="contact-button contact-button-primary" type="submit">Send enquiry <span>↗</span></button>{sent ? <p>{sent}</p> : null}</form></section></main>;
}
