import { useEffect, useState } from "react";
import { apiFetch } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";
import { Permission } from "../../types/auth";

type Contact = { id: number; gymName: string; address: string; phone: string; email: string; openingHours: string; googleMapsUrl: string; instagramUrl: string; facebookUrl: string; whatsAppNumber: string; description: string };
type ContactForm = Omit<Contact, "id">;
const emptyForm: ContactForm = { gymName: "", address: "", phone: "", email: "", openingHours: "", googleMapsUrl: "", instagramUrl: "", facebookUrl: "", whatsAppNumber: "", description: "" };

export function ContactPage() {
  const { hasPermission } = useAuth();
  const [recordId, setRecordId] = useState<number | null>(null);
  const [form, setForm] = useState<ContactForm>(emptyForm);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const canView = hasPermission(Permission.ContactView); const canEdit = hasPermission(Permission.ContactEdit);
  useEffect(() => { if (!canView) { setLoading(false); return; } void (async () => { try { const response = await fetch(`${import.meta.env.VITE_API_URL ?? "http://localhost:5182"}/api/contact`); if (response.status === 404) return; if (!response.ok) throw new Error("Unable to load contact information."); const data = await response.json() as Contact; setRecordId(data.id); setForm(data); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to load contact information." }); } finally { setLoading(false); } })(); }, [canView]);
  function update<K extends keyof ContactForm>(key: K, value: ContactForm[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save() { if (!form.gymName.trim()) { setMessage({ type: "error", text: "Gym name is required." }); return; } if (form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) { setMessage({ type: "error", text: "Enter a valid email address." }); return; } if (!canEdit) { setMessage({ type: "error", text: "You do not have permission to edit contact information." }); return; } setSaving(true); try { const result = await apiFetch<Contact>(recordId ? `/api/contact/${recordId}` : "/api/contact", { method: recordId ? "PUT" : "POST", body: JSON.stringify(form) }); setRecordId(result.id); setForm(result); setMessage({ type: "success", text: "Contact information saved successfully." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to save contact information." }); } finally { setSaving(false); } }
  if (!canView) return <main className="page"><h1>Contact</h1><p>You do not have permission to view this page.</p></main>;
  return <main className="page cms-page"><div className="page-header"><div><h1>Contact Information</h1><p className="muted">Manage the single public contact configuration.</p></div></div>{message ? <p className={`info ${message.type}`}>{message.text}</p> : null}{loading ? <p>Loading contact information…</p> : <section className="card cms-form cms-single-form"><div className="form-grid"><div className="form-field"><label>Gym Name<input value={form.gymName} onChange={(event) => update("gymName", event.target.value)} /></label></div><div className="form-field"><label>Phone<input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></label></div><div className="form-field"><label>Email<input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label></div><div className="form-field"><label>Opening Hours<input value={form.openingHours} onChange={(event) => update("openingHours", event.target.value)} /></label></div></div><div className="form-field"><label>Address<textarea rows={3} value={form.address} onChange={(event) => update("address", event.target.value)} /></label></div><div className="form-grid"><div className="form-field"><label>Google Maps URL<input value={form.googleMapsUrl} onChange={(event) => update("googleMapsUrl", event.target.value)} /></label></div><div className="form-field"><label>WhatsApp Number<input value={form.whatsAppNumber} onChange={(event) => update("whatsAppNumber", event.target.value)} /></label></div><div className="form-field"><label>Instagram URL<input value={form.instagramUrl} onChange={(event) => update("instagramUrl", event.target.value)} /></label></div><div className="form-field"><label>Facebook URL<input value={form.facebookUrl} onChange={(event) => update("facebookUrl", event.target.value)} /></label></div></div><div className="form-field"><label>Description<textarea rows={5} value={form.description} onChange={(event) => update("description", event.target.value)} /></label></div><div className="cms-form-footer cms-form-footer-end"><button className="btn" onClick={save} disabled={saving || !canEdit}>{saving ? "Saving…" : "Save Changes"}</button></div></section>}</main>;
}
