import { useEffect, useState } from "react";
import { apiFetch } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";
import { Permission } from "../../types/auth";

type Testimonial = { id: number; customerName: string; roleOrDescription: string; review: string; rating: number; imageUrl: string; displayOrder: number; isActive: boolean };
type Form = Omit<Testimonial, "id">;
const emptyForm: Form = { customerName: "", roleOrDescription: "", review: "", rating: 5, imageUrl: "", displayOrder: 0, isActive: true };

export function TestimonialsPage() {
  const { hasPermission } = useAuth();
  const [records, setRecords] = useState<Testimonial[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [form, setForm] = useState<Form>(emptyForm);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const canView = hasPermission(Permission.TestimonialsView); const canCreate = hasPermission(Permission.TestimonialsCreate); const canEdit = hasPermission(Permission.TestimonialsEdit); const canDelete = hasPermission(Permission.TestimonialsDelete);
  useEffect(() => { if (!canView) { setLoading(false); return; } void (async () => { try { setRecords(await apiFetch<Testimonial[]>("/api/testimonials/all")); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to load testimonials." }); } finally { setLoading(false); } })(); }, [canView]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function select(id: number) { const item = records.find((record) => record.id === id); if (item) { setSelectedId(id); setForm(item); setMessage(null); } }
  function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.type.startsWith("image/") || file.size > 7 * 1024 * 1024) { setMessage({ type: "error", text: "Choose an image file up to 7 MB." }); return; } const reader = new FileReader(); reader.onload = () => update("imageUrl", typeof reader.result === "string" ? reader.result : ""); reader.onerror = () => setMessage({ type: "error", text: "Unable to read image." }); reader.readAsDataURL(file); }
  async function save() { if (!form.customerName.trim() || !form.review.trim()) { setMessage({ type: "error", text: "Customer name and review are required." }); return; } if (form.rating < 1 || form.rating > 5 || form.displayOrder < 0) { setMessage({ type: "error", text: "Rating must be 1–5 and display order cannot be negative." }); return; } if (selectedId ? !canEdit : !canCreate) { setMessage({ type: "error", text: "You do not have permission to save testimonials." }); return; } setSaving(true); try { const result = await apiFetch<Testimonial>(selectedId ? `/api/testimonials/${selectedId}` : "/api/testimonials", { method: selectedId ? "PUT" : "POST", body: JSON.stringify(form) }); setRecords((current) => (selectedId ? current.map((item) => item.id === result.id ? result : item) : [...current, result]).sort((a, b) => a.displayOrder - b.displayOrder)); setSelectedId(result.id); setForm(result); setMessage({ type: "success", text: "Testimonial saved successfully." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to save testimonial." }); } finally { setSaving(false); } }
  async function remove() { if (!selectedId || !canDelete || !window.confirm("Delete this testimonial?")) return; try { await apiFetch(`/api/testimonials/${selectedId}`, { method: "DELETE" }); setRecords((current) => current.filter((item) => item.id !== selectedId)); setSelectedId(null); setForm(emptyForm); setMessage({ type: "success", text: "Testimonial deleted." }); } catch (error) { setMessage({ type: "error", text: error instanceof Error ? error.message : "Unable to delete testimonial." }); } }
  if (!canView) return <main className="page"><h1>Testimonials</h1><p>You do not have permission to view this page.</p></main>;
  return <main className="page cms-page"><div className="page-header"><div><h1>Testimonials</h1><p className="muted">Manage customer reviews shown on the public website.</p></div></div>{message ? <p className={`info ${message.type}`}>{message.text}</p> : null}{loading ? <p>Loading testimonials…</p> : <div className="cms-layout"><aside className="card cms-list"><button className="btn" onClick={() => { setSelectedId(null); setForm(emptyForm); setMessage(null); }} disabled={!canCreate}>New Testimonial</button>{records.map((item) => <button className={`cms-list-item${item.id === selectedId ? " selected" : ""}`} key={item.id} onClick={() => select(item.id)}><span>{item.displayOrder}. {item.customerName}</span><small>{item.isActive ? "Active" : "Inactive"}</small></button>)}</aside><section className="card cms-form"><div className="form-grid"><div className="form-field"><label>Customer Name<input value={form.customerName} onChange={(event) => update("customerName", event.target.value)} /></label></div><div className="form-field"><label>Role / Description<input value={form.roleOrDescription} onChange={(event) => update("roleOrDescription", event.target.value)} /></label></div></div><div className="form-field"><label>Review<textarea rows={6} value={form.review} onChange={(event) => update("review", event.target.value)} /></label></div><div className="form-field"><label>Image URL</label><div className="image-url-row"><input value={form.imageUrl} onChange={(event) => update("imageUrl", event.target.value)} /><label className="btn btn-secondary upload-button"><input type="file" accept="image/*" onChange={upload} />Upload</label></div></div><div className="form-grid stats-inputs"><div className="form-field"><label>Rating<select value={form.rating} onChange={(event) => update("rating", Number(event.target.value))}>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</select></label></div><div className="form-field"><label>Display Order<input type="number" min="0" value={form.displayOrder} onChange={(event) => update("displayOrder", Number(event.target.value))} /></label></div></div>{form.imageUrl ? <img className="cms-preview-image" src={form.imageUrl} alt="Testimonial preview" /> : null}<div className="cms-form-footer"><label className="toggle-row"><input type="checkbox" checked={form.isActive} onChange={(event) => update("isActive", event.target.checked)} /> Active</label><button className="btn" onClick={save} disabled={saving || (selectedId ? !canEdit : !canCreate)}>{saving ? "Saving…" : selectedId ? "Save Changes" : "Create Testimonial"}</button>{selectedId && canDelete ? <button className="btn btn-danger" onClick={remove}>Delete</button> : null}</div></section></div>}</main>;
}
