import { useEffect, useState } from "react";
import { apiFetch } from "../../api/client";
import { useAuth } from "../../auth/AuthContext";
import { Permission } from "../../types/auth";

type Spotlight = { id: number; memberName: string; quote: string; story: string; imageUrl: string; durationText: string; achievementText: string; displayOrder: number; isActive: boolean; isFeatured: boolean };
type Form = Omit<Spotlight, "id">;
const empty: Form = { memberName: "", quote: "", story: "", imageUrl: "", durationText: "", achievementText: "", displayOrder: 0, isActive: true, isFeatured: false };

export function MemberSpotlightPage() {
  const { hasPermission } = useAuth();
  const [items, setItems] = useState<Spotlight[]>([]);
  const [selected, setSelected] = useState<number | null>(null);
  const [form, setForm] = useState<Form>(empty);
  const [message, setMessage] = useState("");
  const canView = hasPermission(Permission.MemberSpotlightView);
  const canCreate = hasPermission(Permission.MemberSpotlightCreate);
  const canEdit = hasPermission(Permission.MemberSpotlightEdit);
  const canDelete = hasPermission(Permission.MemberSpotlightDelete);
  useEffect(() => { if (canView) void apiFetch<Spotlight[]>("/api/member-spotlights/all").then(setItems).catch((e) => setMessage(e instanceof Error ? e.message : "Unable to load spotlights.")); }, [canView]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.type.startsWith("image/") || file.size > 7 * 1024 * 1024) { setMessage("Choose an image up to 7 MB."); return; } const reader = new FileReader(); reader.onload = () => update("imageUrl", typeof reader.result === "string" ? reader.result : ""); reader.readAsDataURL(file); }
  async function save() { if (!form.memberName.trim()) { setMessage("Member name is required."); return; } if (selected ? !canEdit : !canCreate) return; try { const result = await apiFetch<Spotlight>(selected ? `/api/member-spotlights/${selected}` : "/api/member-spotlights", { method: selected ? "PUT" : "POST", body: JSON.stringify(form) }); setItems((current) => (selected ? current.map((item) => item.id === result.id ? result : item) : [...current, result])); setSelected(result.id); setForm(result); setMessage("Spotlight saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save spotlight."); } }
  async function remove() { if (!selected || !canDelete || !window.confirm("Delete this spotlight?")) return; await apiFetch(`/api/member-spotlights/${selected}`, { method: "DELETE" }); setItems((current) => current.filter((item) => item.id !== selected)); setSelected(null); setForm(empty); setMessage("Spotlight deleted."); }
  if (!canView) return <main className="page"><h1>Member Spotlight</h1><p>You do not have permission to view this page.</p></main>;
  return <main className="page cms-page"><div className="page-header"><div><h1>Member Spotlight</h1><p className="muted">Publish approved member stories without exposing private member records.</p></div></div>{message ? <p className="info success">{message}</p> : null}<div className="cms-layout"><aside className="card cms-list"><button className="btn" disabled={!canCreate} onClick={() => { setSelected(null); setForm(empty); }}>New Spotlight</button>{items.map((item) => <button className={`cms-list-item${selected === item.id ? " selected" : ""}`} key={item.id} onClick={() => { setSelected(item.id); setForm(item); }}><span>{item.displayOrder}. {item.memberName}</span><small>{item.isFeatured ? "Featured" : item.isActive ? "Active" : "Inactive"}</small></button>)}</aside><section className="card cms-form"><div className="form-grid"><div className="form-field"><label>Member name<input value={form.memberName} onChange={(e) => update("memberName", e.target.value)} /></label></div><div className="form-field"><label>Display order<input type="number" min="0" value={form.displayOrder} onChange={(e) => update("displayOrder", Number(e.target.value))} /></label></div></div><div className="form-field"><label>Quote<input value={form.quote} onChange={(e) => update("quote", e.target.value)} /></label></div><div className="form-field"><label>Story<textarea rows={4} value={form.story} onChange={(e) => update("story", e.target.value)} /></label></div><div className="form-grid"><div className="form-field"><label>Duration<input value={form.durationText} onChange={(e) => update("durationText", e.target.value)} /></label></div><div className="form-field"><label>Achievement<input value={form.achievementText} onChange={(e) => update("achievementText", e.target.value)} /></label></div></div><div className="form-field"><label>Image URL</label><div className="image-url-row"><input value={form.imageUrl} onChange={(e) => update("imageUrl", e.target.value)} /><label className="btn btn-secondary upload-button"><input type="file" accept="image/*" onChange={upload} />Upload</label></div></div>{form.imageUrl ? <img className="cms-preview-image" src={form.imageUrl} alt="Spotlight preview" /> : null}<div className="form-grid stats-inputs"><label className="toggle-row"><input type="checkbox" checked={form.isActive} onChange={(e) => update("isActive", e.target.checked)} /> Active</label><label className="toggle-row"><input type="checkbox" checked={form.isFeatured} onChange={(e) => update("isFeatured", e.target.checked)} /> Featured</label></div><div className="cms-form-footer"><button className="btn" disabled={selected ? !canEdit : !canCreate} onClick={() => void save()}>{selected ? "Save Changes" : "Create Spotlight"}</button>{selected && canDelete ? <button className="btn btn-danger" onClick={() => void remove()}>Delete</button> : null}</div></section></div></main>;
}
